site_name: Object Tracker & Area Manager
nav:
    - What is OT&AM?: index.md
    - When should OT&AM be used?: when.md
    - Why should you use OT&AM?: why.md
    - Usages: usage.md
    - Benchmarks: benchmarks.md
    - How does OT&AM work?: how.md
    - Features: features.md
    - API: API.md
    - Settings: settings.md
    - Code examples: code-examples.md
    - Examples: examples.md

theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: purple
    features:
    - instant
repo_url: https://github.com/VerdommeMan/OT-AM
markdown_extensions:
  - admonition
  - pymdownx.critic
extra_css: 
  - css/extras.css